apiVersion: v1
data:
  .gitignore: |-
    *
    !.gitignore
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: private-gpt-llamacpp-cpu
  name: private-gpt-llamacpp-cpu-cm0
  namespace: private-gpt

