apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --profile llamacpp-cpu
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: private-gpt-llamacpp-cpu
  name: private-gpt-llamacpp-cpu
  namespace: private-gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: private-gpt-llamacpp-cpu
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --profile llamacpp-cpu
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: private-gpt-llamacpp-cpu
    spec:
      containers:
        - command:
            - sh
            - -c
            - .venv/bin/python scripts/setup && .venv/bin/python -m private_gpt
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-token
                  key: HF_TOKEN
            - name: PGPT_PROFILES
              value: local
            - name: PORT
              value: "8001"
          image: zylonai/private-gpt:0.6.2-llamacpp-cpu
          name: private-gpt-llamacpp-cpu
          ports:
            - containerPort: 8001
              protocol: TCP
          volumeMounts:
            - mountPath: /home/worker/app/local_data
              name: private-gpt-local-data-pvc
            - mountPath: /home/worker/app/models
              name: private-gpt-models-pvc
      restartPolicy: Always
      volumes:
        - name: private-gpt-local-data-pvc
          persistentVolumeClaim:
            claimName: private-gpt-local-data-pvc
        - name: private-gpt-models-pvc
          persistentVolumeClaim:
            claimName: private-gpt-models-pvc
