apiVersion: v1
data:
  router.yml: |-
    http:
      services:
        ollama:
          loadBalancer:
            healthCheck:
              interval: 5s
              path: /
            servers:
              - url: http://ollama-cpu:11434
              - url: http://ollama-cuda:11434
              - url: http://host.docker.internal:11434

      routers:
        ollama-router:
          rule: "PathPrefix(`/`)"
          service: ollama
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: ollama
  name: ollama-cm1
  namespace: private-gpt
