apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --profile ollama-cuda
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: ollama-cuda
  name: ollama-cuda
  namespace: private-gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ollama-cuda
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --profile ollama-cuda
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: ollama-cuda
    spec:
      containers:
        - image: ollama/ollama:latest
          name: ollama-cuda
      restartPolicy: Always
